language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers

jdk:
  - oraclejdk8

matrix:
  include:
  - env: SBT_VERSION="0.13.18"
  - env: SBT_VERSION="1.2.8"

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "set g8Properties in g8 in Test ~= { _ ++ Map(\"sbt_version\" -> \"$SBT_VERSION\") }" test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
